import type { Metadata } from "next";
import { Geist, Geist_Mono, Oxanium } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"
const geistHeading = Geist({subsets:['latin'],variable:'--font-heading'});

const oxanium = Oxanium({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";
import { CategoryNav } from "@/components/news/category-nav";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", oxanium.variable, geistHeading.variable)}
    >
      <body className="min-h-full flex flex-col paper-bg">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full max-w-6xl mx-auto px-4 py-6 md:py-10 text-black flex-1 flex flex-col">
            <header className="flex justify-center border-b-[3px] border-black pb-4 md:pb-6">
              <Link href="/" className="text-2xl md:text-3xl font-black tracking-tighter flex items-center gap-1 hover:opacity-85 select-none">
                <span className="bg-black text-white px-3 py-1 transform -skew-x-6">KHABAR</span>
              </Link>
            </header>

            <section className="border-[3px] border-black p-4 bg-white/40 backdrop-blur-xs brutal-shadow my-8 flex flex-col md:flex-row gap-4 items-stretch md:items-center">
              <div className="relative flex-1 min-w-[200px] border-2 border-black bg-white flex items-center px-3 py-1.5 focus-within:ring-2 focus-within:ring-black">
                <svg className="w-[18px] h-[18px] text-neutral-500 mr-2 shrink-0" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
                <input 
                  type="text" 
                  placeholder="SEARCH..." 
                  className="w-full bg-transparent border-none outline-none text-xs font-black tracking-wider placeholder-neutral-500"
                />
              </div>

              <CategoryNav />
            </section>

            <div className="flex-1">
              {children}
            </div>

            <footer className="mt-20 border-t-[3px] border-black pt-6 flex flex-col sm:flex-row items-center justify-between gap-4">
              <p className="text-xs font-bold text-neutral-600 uppercase">
                © {new Date().getFullYear()} Khabar. Built in Premium Neo-Brutalist Style.
              </p>
              <div className="text-xs font-black tracking-widest bg-[#e5c158] border-2 border-black px-3 py-1 transform rotate-1 shadow-sm">
                GEOMETRIC & GRID SYSTEM ACTIVE
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
